spring:
  #  docker:
  #    compose:
  #      enabled: true
  #      file: compose-dev.yml
  #      start:
  #        command: up
  #      stop:
  #        command: down
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migrations/{vendor}/
    enabled: true
  cloud:
    aws:
      credentials:
        access-key: "${AWS_ACCESS_KEY:accesskey}"
        secret-key: "${AWS_SECRET_KEY:secretkey}"
      region:
        static: "${AWS_REGION:us-east-2}"
      sqs:
        endpoint: "${AWS_SQS_ENDPOINT:endpoint}"
jwt:
  token:
    key:
      public: "${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqStd8n4SGNM0eZhV/hzU+urHA5/IMZPoP9YQ9ZcLKWiX33nI6bSuZMCrLZcJExf63xS+uxDpGxM8Mnk2zOdl+lPwANXLzP1us5P1PyA3YPycW9J7C5YTQW0GiEL3M93ZX7vMJiVoBYblP3JPlYnoYlBORuc0JPk33KtfEZP+78qXpPHM8imYrJLe8ceiDLLFDU/nh5KC2dWAy3ci1ahoJ1Q9ELhp3IZLvOTX57H/T2VKOYOya5+ST41h+JjzI+qGTVnLcKaW+k25YLlVnkSspvdx98+yQDi7kbOTS6yRZHUPD6wPk/nUozpD0nZKccoH4W+zMwmQVtsAA6JCA9gfGwIDAQAB}"

app:
  docs-api-url: "${DOCS_API_URL:(no value)}"
  aws:
    access-key: "${AWS_ACCESS_KEY:no_access_key}"
    secret-key: "${AWS_SECRET_KEY:no_secret_key}"
    session-token: "${AWS_SESSION_TOKEN:}"
    dynamodb:
      endpoint: "${AWS_DYNAMODB_ENDPOINT:dynamodb.us-east-1.amazonaws.com}"

server:
  port: 8082
  servlet:
    context-path: "/production"
