package br.com.grupo63.serviceproduction.gateway.status.entity;

import br.com.grupo63.serviceproduction.entity.status.OrderStatus;
import br.com.grupo63.serviceproduction.entity.status.Status;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter

@DynamoDBTable(tableName = "status")
public class StatusPersistenceEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private boolean deleted;

    @DynamoDBAttribute
    private int order;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "status")
    private OrderStatus status;

    @DynamoDBAttribute(attributeName = "lastUpdateDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime lastUpdateDate;

    public StatusPersistenceEntity(Status status) {
        this.id = status.getId();
        this.deleted = status.isDeleted();
        this.order = status.getOrder();
        this.status = status.getStatus();
        this.lastUpdateDate = LocalDateTime.now();
    }

    public Status toModel() {
        return new Status(this.getId(), this.isDeleted(), this.getOrder(), this.getStatus());
    }
}
